name: team1
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hexcolor: ^3.0.1
  bot_toast: ^4.0.3
  fluttertoast: ^8.1.1
  flutter_iconly: ^1.0.2
  intl: ^0.17.0
  conditional_builder_null_safety: ^0.0.6
  carousel_slider: ^4.1.1
  flutter_launcher_icons: ^0.10.0
  splash_screen_view: ^3.0.0
  timeago: ^3.3.0

  # firebase
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.0.3
  firebase_messaging: ^14.0.3



#flutter_icons:
#  android: true
#  ios: true
#  image_path: "assets/images/s.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
